import {addDays,weekday,difference} from './time.js';
export const foundations=['Java contracts and return values','Arrays, strings, and collection operations','Complexity and brute-force analysis','Hashing and equality','Merge sort and stable merging','Partitioning and quicksort','Recursion and stack frames'];
export function makePlan(questions,settings){
 const start=settings.start,days=Array.from({length:90},(_,i)=>({date:addDays(start,i),number:i+1,capacity:Number(settings.capacity[weekday(addDays(start,i))]),questions:[],lesson:i<7?foundations[i]:null,mock:[28,42,56,78,80,82,84,87,89].includes(i+1),light:weekday(addDays(start,i))===0}));
 const groups=[[],[],[],[],[]];const early=[217,242,1,125,26,283,303];
 questions.filter(q=>q.tier==='Core').forEach(q=>{let g=early.includes(q.id)?0:q.pattern<=8?1:q.pattern<=25?2:q.pattern<=31?3:4;groups[g].push(q);});
 const ranges=[[0,6],[7,20],[21,41],[42,62],[63,76]];
 groups.forEach((items,g)=>{items.sort((a,b)=>a.pattern-b.pattern||a.estimate-b.estimate||a.order-b.order);const [lo,hi]=ranges[g];let cursor=lo;let remaining=items.reduce((n,q)=>n+q.estimate,0);for(const q of items){const remainingDays=days.slice(cursor,hi+1).filter(d=>!d.light);const weight=remainingDays.reduce((n,d)=>n+Math.max(15,d.capacity*.75-20-(d.mock?60:0)),0);while(cursor<hi&&(days[cursor].light||days[cursor].questions.reduce((n,id)=>n+questions.find(x=>x.id===id).estimate,0)>=Math.max(q.estimate/2,remaining*Math.max(15,days[cursor].capacity*.75-20-(days[cursor].mock?60:0))/Math.max(1,weight))))cursor++;days[cursor].questions.push(q.id);remaining-=q.estimate;}});
 return days.map(d=>{d.newMinutes=d.questions.reduce((n,id)=>n+questions.find(q=>q.id===id).estimate,0);d.reviewMinutes=Math.max(20,Math.ceil((d.newMinutes+(d.mock?60:0)+(d.lesson?15:0))/3));d.total=d.newMinutes+d.reviewMinutes+(d.mock?60:0)+(d.lesson?15:0);d.overflow=Math.max(0,d.total-d.capacity);return d;});
}
export function catchUp(plan,questions,state,today){let dates=plan.filter(d=>d.date>=today&&d.number<=77&&!state.pauses?.[d.date]).map(d=>({...d,free:Math.max(0,d.capacity-d.reviewMinutes-(d.lesson?15:0)-(d.mock?60:0)),assigned:[]}));const pending=[...new Set([...plan.filter(d=>d.number<=77).flatMap(d=>d.questions),...(state.backlog||[])])].filter(id=>!state.attempts.some(a=>a.question===id));const unresolved=[];for(const id of pending){const q=questions.find(q=>q.id===id),day=dates.find(d=>d.free>=q.estimate);if(day){day.assigned.push(id);day.free-=q.estimate;}else unresolved.push(id);}return {days:dates,unresolved};}
export const planDay=(settings,today)=>difference(today,settings.start)+1;
