export const SCHEMA=1;
export const keyFor=path=>'dsa-forge:v1:'+path.replace(/index\.html$/,'').replace(/\/+$/,'/');
export function blank(){return {schema:SCHEMA,curriculum:'2026-09-23',rev:0,settings:null,plan:[],attempts:[],events:[],notes:{},bookmarks:[],reviews:{},corrections:{},sessions:[],timer:null,attemptTimer:null,cards:[],history:[],missions:{},deferred:[],mocks:[],pauses:{},conflicts:[]};}
export function validate(s){if(!s||s.schema!==SCHEMA)throw Error('Unsupported backup version. This app accepts schema 1.');for(const k of ['attempts','events','sessions','bookmarks','cards','history','plan','deferred','mocks','conflicts'])if(!Array.isArray(s[k]))throw Error('Invalid backup: '+k);for(const k of ['notes','reviews','corrections','missions','pauses'])if(!s[k]||typeof s[k]!=='object'||Array.isArray(s[k]))throw Error('Invalid backup: '+k);if(s.settings){if(!Array.isArray(s.settings.capacity)||s.settings.capacity.length!==7||s.settings.capacity.some(x=>!Number.isFinite(x)||x<0||x>1440))throw Error('Invalid study capacity');new Intl.DateTimeFormat('en',{timeZone:s.settings.zone});if(!/^\d{4}-\d{2}-\d{2}$/.test(s.settings.start))throw Error('Invalid start date');}for(const a of s.attempts)if(typeof a.id!=='string'||!Number.isFinite(a.question)||typeof a.note!=='string')throw Error('Invalid attempt');for(const n of Object.values(s.notes))if(typeof n!=='object'||typeof n.text!=='string')throw Error('Invalid note');const str=(v)=>typeof v==='string',num=(v)=>Number.isFinite(v),obj=(v)=>v&&typeof v==='object'&&!Array.isArray(v),date=(v)=>str(v)&&/^\d{4}-\d{2}-\d{2}$/.test(v);
 const safeUrl=v=>!v||(str(v)&&/^https:\/\//.test(v));
 for(const c of s.cards)if(!obj(c)||!str(c.id)||!str(c.title)||!str(c.explanation)||!safeUrl(c.sourceUrl))throw Error('Invalid personal card');
 for(const e of s.events)if(!obj(e)||!str(e.id)||!date(e.day)||!str(e.note))throw Error('Invalid learning event');
 for(const r of Object.values(s.reviews))if(!obj(r)||!date(r.due)||!num(r.confidence))throw Error('Invalid review');
 for(const x of s.sessions)if(!obj(x)||!str(x.id)||!num(x.minutes)||!Array.isArray(x.splits)||x.splits.some(y=>!date(y.day)||!num(y.minutes)))throw Error('Invalid session');
 for(const d of s.plan)if(!obj(d)||!date(d.date)||!Array.isArray(d.questions)||!num(d.capacity)||!num(d.number)||!num(d.total))throw Error('Invalid plan');
 for(const m of s.mocks)if(!obj(m)||!str(m.id)||!Array.isArray(m.questions)||!num(m.started)||!num(m.minutes)||!safeUrl(m.custom)||(m.finished&&!obj(m.rubric)))throw Error('Invalid mock');
 for(const n of Object.values(s.notes))if(!safeUrl(n.url)||(n.revisions&&!Array.isArray(n.revisions)))throw Error('Invalid note metadata');
 for(const d of s.deferred)if(!obj(d)||!num(d.question)||!str(d.reason))throw Error('Invalid deferral');
 for(const c of s.conflicts)if(!obj(c)||!str(c.id)||!str(c.note))throw Error('Invalid preserved conflict');
 if(s.timer&&(!obj(s.timer)||!str(s.timer.id)||!num(s.timer.started)||!num(s.timer.duration)||!['focus','break'].includes(s.timer.kind)))throw Error('Invalid timer');
 return s;}
export function parseBackup(raw){if(new TextEncoder().encode(raw).length>8*1024*1024)throw Error('Backup exceeds 8 MB limit');return validate(JSON.parse(raw));}
const union=(a,b)=>[...new Map([...a,...b].map(x=>[x.id,x])).values()];
export function merge(a,b){const out=structuredClone(a);for(const k of ['attempts','events','sessions','cards','history','deferred','mocks','conflicts'])out[k]=union(a[k],b[k]);out.bookmarks=[...new Set([...a.bookmarks,...b.bookmarks])];for(const [id,n] of Object.entries(b.notes)){if(out.notes[id]&&out.notes[id].text!==n.text)out.conflicts.push({id:crypto.randomUUID(),question:id,note:n.text,code:n.code||'',at:Date.now(),reason:'Imported note differs; current note retained'});else out.notes[id]=n;}for(const [id,r] of Object.entries(b.reviews)){if(!out.reviews[id]||r.due<out.reviews[id].due)out.reviews[id]=r;}out.history.push({id:crypto.randomUUID(),at:Date.now(),action:'Merged backup; current plan/settings retained. Conflicting notes preserved.'});return out;}
export function createStore(path,storage){const key=keyFor(path);let state=blank(),fault=null,raw=null;try{storage=storage||globalThis.localStorage;raw=storage.getItem(key);if(raw)state=validate(JSON.parse(raw));}catch(e){fault=e;}
 const listeners=[];function inform(){listeners.forEach(f=>f(state));}
 async function change(fn){if(fault)throw Error('Storage needs recovery. Export the raw data or restore a backup in Settings.');const run=()=>{let latest;try{const r=storage.getItem(key);latest=r?validate(JSON.parse(r)):blank();}catch(e){fault=e;throw e;}const next=structuredClone(latest);const replacement=fn(next);const final=replacement||next;final.rev=latest.rev+1;validate(final);const payload=JSON.stringify(final);try{storage.setItem(key+':previous',JSON.stringify(latest));storage.setItem(key,payload);}catch(e){throw Error('Save failed: storage unavailable or full. Export your data before closing.');}state=final;inform();return state;};if(globalThis.navigator?.locks)return navigator.locks.request(key,run);if(globalThis.window)throw Error('This browser lacks Web Locks. Use a current Chrome, Edge, Firefox, or Safari over HTTPS to protect multi-tab writes.');return run();}
 if(globalThis.window)window.addEventListener('storage',e=>{if(e.key===key&&e.newValue){try{state=validate(JSON.parse(e.newValue));inform();}catch{fault=Error('Another tab wrote unreadable state.');}}});
 return {key,get:()=>state,change,on:f=>listeners.push(f),fault:()=>fault,raw:()=>raw,recover:async s=>{validate(s);if(raw)storage.setItem(key+':damaged:'+Date.now(),raw);storage.setItem(key,JSON.stringify(s));fault=null;state=s;inform();},previous:()=>storage.getItem(key+':previous'),bytes:()=>new TextEncoder().encode(JSON.stringify(state)).length};}
